[package]
name = "marine"
publish = ["fluence"]
version = "0.1.7"
edition = "2021"

[[bin]]
name = "marine"
path = "src/main.rs"

[dependencies]
release-flow-demo-a = { version = "0.6.8", registry = "fluence", path = "../crates/release-flow-demo-a" }
