[package]
name = "release-flow-demo-c"
publish = ["fluence"]
version = "0.2.2"
edition = "2021"

[dependencies]
serde = { version = "1.0.146", features = ["derive"] }
serde_json = "1.0.89"
serde_derive = "1.0.147"
serde_with = "2.1.0"
