[package]
name = "release-flow-demo-b"
publish = ["fluence"]
version = "0.4.0"
edition = "2021"

[dependencies]
serde = "1.0.146"
toml = "0.5.8"
release-flow-demo-c = { version = "0.2.5", registry = "fluence", path = "../release-flow-demo-c" }
