[package]
name = "release-flow-demo-b"
publish = ["fluence"]
version = "0.3.2"
edition = "2021"

[dependencies]
rerde = "1.0.146"
toml = "0.5.8"
release-flow-demo-c = { version = "0.2.0", registry = "fluence", path = "../release-flow-demo-c" }

[package.metadata.workspaces]
independent = true
