[package]
name = "release-flow-demo-a"
publish = ["fluence"]
version = "0.3.5-alpha.0"
edition = "2021"

[dependencies]
release-flow-demo-b = { version = "0.2.4", registry = "fluence", path = "../release-flow-demo-b" }

[package.metadata.workspaces]
independent = true
