[package]
name = "release-flow-demo-a"
publish = ["fluence"]
version = "0.6.8"
edition = "2021"

[dependencies]
release-flow-demo-b = { version = "0.4.1", registry = "fluence", path = "../release-flow-demo-b" }
prometheus-client = "0.18.0"
