name: release-please-rust

on:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  release-please:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          config-file: .github/release-please/rust-config.json
          manifest-file: .github/release-please/rust-manifest.json

      - name: Checkout
        if: steps.release.outputs.releases_created
        uses: actions/checkout@v3

      - name: Import secrets
        if: steps.release.outputs.releases_created
        uses: hashicorp/vault-action@v2.4.3
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/cargo-registry/users/ci token | CARGO_REGISTRIES_FLUENCE_TOKEN

      - name: Setup Rust toolchain
        if: steps.release.outputs.releases_created
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-workspaces
        if: steps.release.outputs.releases_created
        uses: baptiste0928/cargo-install@v1.3.0
        with:
          crate: cargo-workspaces

      - name: Build
        if: steps.release.outputs.releases_created
        run: cargo build --release

      - name: Publish
        if: steps.release.outputs.releases_created
        run: cargo workspaces publish --from-git
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: debug
        run: echo ${{ toJSON(steps.release.outputs) }}

      - name: Upload marine binary
        if: steps.release.outputs['packages/marine--release_created']
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/marine
          tag_name: ${{ steps.release.outputs['packages/marine--tag_name'] }}
